### ISSUE TITLE
About wilddeepfake dataset

### ISSUE THREAD

**Issue by githuboflk** [VISION-SJTU/RECCE#11]
Thank you for your crop code. It is very helpful to me. But the wilddeepfake team seems to be unreachable. Could you please share a link to find a data set to download? Google cloud disk or Baidu cloud disk can be. Thanks a million.

**Comment by XJay18** [comment]
Hi,
It seems that WildDeepfake is currently out of maintenance, but I do not know the reason. Fortunately, the original download link for this dataset is still available. To respect the regulations of the original dataset, please send me a request through your academic email and I will send the download link for WildDeepfake to you.

Thanks for your understanding.

**Comment by Ruhangs** [comment]
> Hi, It seems that WildDeepfake is currently out of maintenance, but I do not know the reason. Fortunately, the original download link for this dataset is still available. To respect the regulations of the original dataset, please send me a request through your academic email and I will send the download link for WildDeepfake to you.
> 
> Thanks for your understanding.

Hello, I have the same situation. Can you tell me your academic email? I will send you a request through my academic email. Thanks

**Comment by XJay18** [comment]
Hi, please send emails to `junyicao@sjtu.edu.cn` if you need the download link of WildDeepfake dataset.
Best wishes.

**Comment by XJay18** [comment]
Close due to inactivation. Please feel free to reopen this issue if you still have related problems.
