### ISSUE TITLE
the result of the first epoch on Celeb-DF is very high

### ISSUE THREAD

**Issue by zhongjian1999** [VISION-SJTU/RECCE#12]
Hello!
Thank you for your excellent work. I use the preprogressed Celeb-DF dataset provided in #9 and start training successfully, but the result of the first epoch is: ACC 0.9712, AUC 0.9957, seems too high at the beginning. Is it normal? I noticed the program will spilt dataset into train set and test set before training, so is it necessary to split the dataset manually?
Thank you for your help, and waiting for your answer.

**Comment by XJay18** [comment]
Hi,
I think this is normal since intra-testing results for Celeb-DF are quite saturated. The training and testing sets are split according to the `List_of_testing_videos.txt` file included in the dataset, so you do not need to manually split the data.
