### ISSUE TITLE
The data structure of the datasets

### ISSUE THREAD

**Issue by mirro-yyf** [VISION-SJTU/RECCE#13]
Thank you for your crop code. It is very helpful to me. But I have some questions about the structure of the dataset. Would you please provide the data structure of the dataset? The following picture is the dataset structure of F3-NET. Is this the same with the dataset structure of RECCE framework?
![dataset_structure](https://user-images.githubusercontent.com/89956031/220242606-9bb25cfb-d13d-4067-8849-0b307cb51750.png)

**Comment by XJay18** [comment]
Hi, the folder structure for FaceForensics++ dataset in this repo follows the [original structure](https://github.com/ondyari/FaceForensics/tree/master/dataset) specified by the official github.

**Comment by XJay18** [comment]
Close due to inactivation. Please feel free to reopen this issue if you still have related problems.
