### ISSUE TITLE
Dataset downloading issues

### ISSUE THREAD

**Issue by mamarasulovs** [VISION-SJTU/RECCE#16]
I downloaded not the full FaceForensics++ dataset, but a 9GB dataset from Kaggle, extracted faces from the videos in the "deepfakes" directory, and placed them in the training and testing subfolders.
Does this method also work? Is it wrong?

**Comment by XJay18** [comment]
Hi, sorry for the late reply. The dataset you download may have a different dataset structure from the original  FaceForensics++. I think you could create a custom dataloader inherited from [AbstractDataset](https://github.com/VISION-SJTU/RECCE/blob/58cabeb7a0fef31a202334ff0b8f2a285e69d393/dataset/abstract_dataset.py#L10). 

The custom dataloader should fill `self.images` and `self.targets` properly according to your specific dataset structure. `self.images` is a list of strings specified the corresponding image path while `self.targets` is a list of integers specified the label of the corresponding image.
Then, add a new key-value pair in [this dictionary](https://github.com/VISION-SJTU/RECCE/blob/58cabeb7a0fef31a202334ff0b8f2a285e69d393/dataset/__init__.py#L7) for registering the custom dataloader.
Lastly, specified the dataloader name in the [model configuration file](https://github.com/VISION-SJTU/RECCE/tree/58cabeb7a0fef31a202334ff0b8f2a285e69d393/config#model--configuration), ie, `data/name` entry.

After these steps, you may use the custom dataloader for training using RECCE.

**Comment by XJay18** [comment]
Close due to inactivation. Please feel free to reopen this issue if you still have related problems.
