### ISSUE TITLE
would you provide pre-train model

### ISSUE THREAD

**Issue by Pudge-tao** [VISION-SJTU/RECCE#17]
in closed issues, i have only found FF++ dataset pickle, can u provide your pre-train model ("best_model.bin"). when running the code to test,i got errors that means “theres no model file”。thanks a lot
![image](https://user-images.githubusercontent.com/49672927/228785992-a2fb0157-4ad7-4cf8-9c9a-18fe3317382a.png)
![image](https://user-images.githubusercontent.com/49672927/228786214-f2e4f57c-1003-4331-b71e-515ce84ea761.png)

**Comment by Zz-ww** [comment]
我也遇到了同样的问题

**Comment by XJay18** [comment]
Hi, sorry for the late reply. The provided RECCE weighs are the model parameters which could be used for testing. The 'bin' file is just used for debugging which contains some additional information. 

You can convert the provided RECCE weights stored in 'pickle' file to 'bin' file using the code below.

```python
import torch
import argparse


def arg_parser():
    parser = argparse.ArgumentParser(description="pickle2bin utility")
    parser.add_argument("--path", "-p",
                        type=str,
                        required=True,
                        help="Specify the path of the pickle file to "
                             "translate into bin file.")
    return parser.parse_args()


if __name__ == '__main__':
    arg = arg_parser()

    print(f"Loading pickle file from '{arg.path}'.")
    model_params = torch.load(arg.path, map_location="cpu")

    torch.save({
        "model": model_params,
        "step": -1,
        "best_step": -1,
        "best_metric": torch.tensor(-1.),
        "eval_metric": "Unknown"
    }, arg.path.replace(".pickle", ".bin"))
    print(f"Converted pickle file to bin file stored in "
          f"'{arg.path.replace('.pickle', '.bin')}'.")
```

Supposed you have named the above code as `pickle2bin.py`, you can run
```bash
python pickle2bin.py --path model_params_ffpp_c40.pickle
```
to translate the 'pickle' weights into 'bin' file for testing. Please also note that you may need to modify the value of `config/ckpt` in the [model configuration file](https://github.com/VISION-SJTU/RECCE/tree/58cabeb7a0fef31a202334ff0b8f2a285e69d393/config#model--configuration), ie, replace the default value `best_model_1000` to `model_params_ffpp_c40`.

**Comment by Pudge-tao** [comment]
> 我也遇到了同样的问题

太难了

> Hi, sorry for the late reply. The provided RECCE weighs are the model parameters which could be used for testing. The 'bin' file is just used for debugging which contains some additional information.
> 
> You can convert the provided RECCE weights stored in 'pickle' file to 'bin' file using the code below.
> 
> ```python
> import torch
> import argparse
> 
> 
> def arg_parser():
>     parser = argparse.ArgumentParser(description="pickle2bin utility")
>     parser.add_argument("--path", "-p",
>                         type=str,
>                         required=True,
>                         help="Specify the path of the pickle file to "
>                              "translate into bin file.")
>     return parser.parse_args()
> 
> 
> if __name__ == '__main__':
>     arg = arg_parser()
> 
>     print(f"Loading pickle file from '{arg.path}'.")
>     model_params = torch.load(arg.path, map_location="cpu")
> 
>     torch.save({
>         "model": model_params,
>         "step": -1,
>         "best_step": -1,
>         "best_metric": torch.tensor(-1.),
>         "eval_metric": "Unknown"
>     }, arg.path.replace(".pickle", ".bin"))
>     print(f"Converted pickle file to bin file stored in "
>           f"'{arg.path.replace('.pickle', '.bin')}'.")
> ```
> 
> Supposed you have named the above code as `pickle2bin.py`, you can run
> 
> ```shell
> python pickle2bin.py --path model_params_ffpp_c40.pickle
> ```
> 
> to translate the 'pickle' weights into 'bin' file for testing. Please also note that you may need to modify the value of `config/ckpt` in the [model configuration file](https://github.com/VISION-SJTU/RECCE/tree/58cabeb7a0fef31a202334ff0b8f2a285e69d393/config#model--configuration), ie, replace the default value `best_model_1000` to `model_params_ffpp_c40`.

thanks a lot，It helps me a lot

> 

thanks a lot, it helps me a lot

**Comment by ucalyptus2** [comment]
@Pudge-tao what is the name of the pickle file and where to find it?

**Comment by ats4869** [comment]
> @Pudge-tao what is the name of the pickle file and where to find it?

chat18.aichatos.xyz/#/chat/1698070039905
