### ISSUE TITLE
About the link of celeb-DF.

### ISSUE THREAD

**Issue by LonelyPlanetIoT** [VISION-SJTU/RECCE#19]
Hi,Do you still keep the preprocessed celeb-DF dataset which provided by the link above        Thank you

_Originally posted by @SaharHusseini in https://github.com/VISION-SJTU/RECCE/issues/9#issuecomment-1398137619_

**Comment by XJay18** [comment]
Hi, I currently do not have enough quota to store the preprocessed Celeb-DF. You may request the dataset from the [original repo](https://github.com/yuezunli/celeb-deepfakeforensics). You may refer to #1 for extracting frames from the video data.
