### ISSUE TITLE
FF++c40 pretrained model 

### ISSUE THREAD

**Issue by Blosslzy** [VISION-SJTU/RECCE#21]
Can you provide the weight pretrained in the FF++c40, thank you very much!

**Comment by Blosslzy** [comment]
I have found the pre-trained weight you have provided, thank you very much!

**Comment by QuanLNTU** [comment]
> I have found the pre-trained weight you have provided, thank you very much!

Hello, can you send me the processed FF++dataset? 
Thank you very much. My email is lntu_llq@163.com
