### ISSUE TITLE
处理过的FF++数据集能发给我一份吗？

### ISSUE THREAD

**Issue by QuanLNTU** [VISION-SJTU/RECCE#22]
作者您好，非常感谢您的工作，此工作对我帮助很大，您能发一份处理过的FF++数据集给我吗？
万分感谢！！！
我的email：lntu_llq@163.com

**Comment by XJay18** [comment]
Done. Please check your email.

Best wishes

**Comment by long280** [comment]
作者您好，非常感谢您的工作，这项工作对我有很大帮助，能麻烦您也发一份处理过的FF++数据集给我吗？万分感谢我的
电子邮件
1535472424@qq.com
