### ISSUE TITLE
关于预处理的FF++数据集

### ISSUE THREAD

**Issue by siyouguo** [VISION-SJTU/RECCE#23]
我听说您已经处理过FF++数据集，由于CPU的限制，我并不能完成数据集的预处理，我非常希望能够获取您处理过的数据集，以满足我的研究需求。如果可能，我将万分感激！您可以通过电子邮件联系我，我的邮箱是：sdut_siyouguo@163.com

**Comment by VoyageWang** [comment]
> 我听说您已经处理过FF++数据集，由于CPU的限制，我并不能完成数据集的预处理，我非常希望能够获取您处理过的数据集，以满足我的研究需求。如果可能，我将万分感激！您可以通过电子邮件联系我，我的邮箱是：[sdut_siyouguo@163.com](mailto:sdut_siyouguo@163.com)

你好如果你能分享给我的话我也将万分感谢您，我的邮箱是 voyagewang@foxmail.com

**Comment by long280** [comment]
你好，如果你能分享给我的话我也将万分感谢你，我的邮箱是1535472424@qq.com

**Comment by zhongyi11** [comment]
你好，如果你能分享给我的话我也将万分感谢你，我的邮箱是1770133850@qq.com
