### ISSUE TITLE
作者您好，请问本项目支持部署在fastdeploy上吗？

### ISSUE THREAD

**Issue by QuanLNTU** [VISION-SJTU/RECCE#26]
作者您好，请问本项目支持部署在fastdeploy上吗？
谢谢！

**Comment by XJay18** [comment]
Sorry for the late reply. 
I do not have much experience with FastDeploy of PaddlePaddle. You may need to perform some conversions from PyTorch to PaddlePaddle.

**Comment by XJay18** [comment]
Close due to inactivation. Please feel free to reopen this issue if you still have related problems.
