### ISSUE TITLE
Questions Regarding Model Training Requirements and Dataset 

### ISSUE THREAD

**Issue by ajpsifadiosf** [VISION-SJTU/RECCE#28]
I am interested in your RECCE project  and have a few questions regarding the training requirements and dataset preparation:
1. Minimum hardware requirements for training:
Could you please specify the least GPU that can be used for training? Is it possible to train the model using a single 3090 GPU?
2. Regarding the dataset preparation, I extract the images using c40. But the dataset is still very larage. Could you provide an estimate of the final size of the datasest after the extraction?

**Comment by XJay18** [comment]
Hi, thanks for your interest in our project.
1. In experiments, we used multiple 2080Ti GPUs, and I think a single 3090 is also sufficient to run the code. If you encounter an "out of GPU memory" issue, you can decrease the batch size.
2. After preprocessing (extracting images from videos, face alignment, and cropping), we got about 55G data (double-checked) for FaceForensics++ c23 and c40 in total.

**Comment by ajpsifadiosf** [comment]
Thank you for your response！We tried using RetinaFace as you mentioned to extract the facial images from the sequences and store image, but we found that it seems that RetinaFace can only process images. How did you process the video?

**Comment by XJay18** [comment]
Hi, to process the video, you may need to extract frames from each sequence first. This can be done with the `cv2.VideoCapture` API.

**Comment by XJay18** [comment]
Close due to inactivation. Please feel free to reopen this issue if you still have related problems.
