### ISSUE TITLE
data pre-processing and dataset initialization

### ISSUE THREAD

**Issue by MZMMSEC** [VISION-SJTU/RECCE#3]
Hi,

thanks for your sharing the codes! I have some questions about the data pre-processing and dataset initialization: 1. in the FaceForensics class in faceforensics.py, what is the '.pickle' file? and would you please provide this file? 2. how many frames per video do you extracted for detecting the face  and  further for training? especially how to balance the data number between the real videos and fake videos?(that is, extract the same number of frames first and then balance them in the training or extract the different number of frames at the begining for data balance?)

thanks~!

**Comment by XJay18** [comment]
Hi, the pickle files just store the image paths and binary labels for experiments. You may use your own dataloder to load images.

We extract roughly the same number of frames per video for detecting the face and store the cropped faces. We sample about 12 frames per manipulated video for training, which results in 36,000 (=~12.5 frames/video×720 videos×4 manipulated techniques) fake images. The number of real images used for training is also 36,000 (=~50 frames/video×720 videos).

**Comment by MZMMSEC** [comment]
> Hi, the pickle files just store the image paths and binary labels for experiments. You may use your own dataloder to load images.
> 
> We extract roughly the same number of frames per video for detecting the face and store the cropped faces. We sample about 12 frames per manipulated video for training, which results in 36,000 (=~12.5 frames/video×720 videos×4 manipulated techniques) fake images. The number of real images used for training is also 36,000 (=~50 frames/video×720 videos).

Hi, sorry to bother you again! Recently, I was doing some experiments and research by using your provided codes. However, when I use your data processing codes, mentioned in #1,  to crop the faces from videos, I didn't get the same or similar results (e.g. face size) of extracted faces, as your provided processed datasets, mentioned in #2. As mentioned in many papers, a differerent face pre-processing will lead to a drop performance on the original model.

So, I would like to request for your face preprocessing codes with the detailed parameters settings.

Thanks!

**Comment by XJay18** [comment]
Hi, unfortunately, I am not able to retrieve the specific parameter settings for FF++ preprocessing because it's been too long since the preprocessing task.

**Comment by MZMMSEC** [comment]
> Hi, unfortunately, I am not able to retrieve the specific parameter settings for FF++ preprocessing because it's been too long since the preprocessing task.

thanks all the same!

**Comment by IIyaJ** [comment]
help！How do you generate pickle files? Mine is always reading pickle files and reporting errors. Are there any format requirements
