### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by sizhuanger** [VISION-SJTU/RECCE#30]
Hello, Thanks for your work very much, can you share the processed datasets(including FF++,  Celeb-DF) for me?  my email is 2517800116@qq.com.

**Comment by XJay18** [comment]
Done. Please check your email.

**Comment by ts1ioy** [comment]
您好！同求一份处理后的数据集，我的邮箱是3290516033@qq.com，十分感谢！

**Comment by httpswlt** [comment]
Hello, Thanks for your job. I also have some data issues. Can you share the processed datasets(including FF++, Celeb-DF) for me? My email is 962578230@qq.com
