### ISSUE TITLE
about dataset of Celeb-DF , WildDeepfake and DFDC

### ISSUE THREAD

**Issue by long280** [VISION-SJTU/RECCE#32]
Hello,Thanks for your work very much. Can you spare the processed dataset of Celeb-DF, DFDC and WildDeepfake to me? Best wishes!

**Comment by XJay18** [comment]
Hi, for these dataset requests, please send me an email (`junyicao@sjtu.edu.cn`) through your institutional email. Thanks.

**Comment by ts1ioy** [comment]
您好！同求一份处理后的数据集（FF++,Celeb-DF），我的邮箱是[3290516033@qq.com](mailto:3290516033@qq.com)，十分感谢！
