### ISSUE TITLE
About processed dataset of WildDeepfake and DFDC

### ISSUE THREAD

**Issue by VX-Anh** [VISION-SJTU/RECCE#33]
Hello. Thanks for your work very much.
I sent an email to junyicao@sjtu.edu.cn through my institutional email to you but it seems there was a problem that prevented the email from being sent. Can you send me the DFDC and WildDeepfake processed dataset? 
My institutional email is 21C11002@student.hcmus.edu.vn and my personal email is xuananhbkcqt@gmail.com.
Wishing you all the best!

**Comment by XJay18** [comment]
Hi, Anh, I've sent you an email a few days before (to the address `thuvienphapluat.com`). Did you receive it?

Best regards,
Junyi

**Comment by VX-Anh** [comment]
Hi Junyi, I just checked and saw that I received an email from you. Thanks you very much.

Wishing you all the best!
