### ISSUE TITLE
test results on ff++

### ISSUE THREAD

**Issue by YinqiCai** [VISION-SJTU/RECCE#38]
Hi, thanks for your excellent work!
I follow your face crop code and use the first 50 frames of each video, and then I test the ff++_c23 and c40 with the trained weight you provided, the results are lower:
c23:
```
Test, FINAL LOSS 0.2105, FINAL ACC 0.9169, FINAL AUC 0.9860
# EER: 0.0605(thresh: 0.2734)
```
c40:
```
Test, FINAL LOSS 0.4998, FINAL ACC 0.8063, FINAL AUC 0.8546
# EER: 0.2227(thresh: 0.7976)
```
I also try to use 50 frames of the first 150 frames to test, the results are similar.
Can you help me find out what's wrong? Thanks for your nice work again and I am looking forward to your reply.

**Comment by XJay18** [comment]
Hi, sorry for the late reply. A common problem is the difference in data preprocessing, including frame extraction, face alignment & cropping, etc. Also make sure the deployment environment is similar to that stated in the README. Feel free to email me for our preprocessed data if you would like to minimize some factors from the data end that may cause the discrepancy.
