### ISSUE TITLE
关于处理后的数据集获取

### ISSUE THREAD

**Issue by Cherxy** [VISION-SJTU/RECCE#47]
作者您好，我也想获取您处理后的数据集，非常感谢您的帮助，我的邮箱是：s23150812015@smail.cczu.edu.cn

**Comment by XJay18** [comment]
Thanks for your interest! Please check your email.

**Comment by bandaidssssss** [comment]
> Thanks for your interest! Please check your email.
作者您好，我也想获取您处理后的数据集，感谢您的帮助。我的邮箱是106005748@qq.com
